---
title: "Details"
output: html_document
---

`r top_level_image('fallen-tree-garden.jpg', 'Fallen Tree Farm')`

-   [Location](#location)
-   [Time and date](#time-and-date)
-   [Directions](#directions)
-   [Hotels](#hotels)

## Location

[Fallen Tree Farm](http://www.fallentreefarm.com/)

1634 Holly Pike, Carlisle, PA 17015

## Time and date

The ceremony will begin at 4 PM on October 7^th^, 2017. A cocktail reception
will follow the ceremony at the same location.

## Directions

### From Philadelphia

-   Get onto I-76W towards Harrisburg
-   Take exit 247 to merge onto I-283
-   Use the left lane to take exit 3A onto I-83 S toward Harrisburg
-   After the crossing the bridge over the Susquehanna, stay in the left lanes
    to continue on PA-581 W
-   Use the left lane to take exit 1B and merge onto I-81 S toward Carlisle
-   Take exit 47A and merge onto PA-34 S (South Hanover St)
-   Follow PA-34 S for 2.8 miles
-   Turn right into the long driveway for Fallen Tree Farm

### From Pittsburgh

-   Get onto I-76 E towards Harrisburg
-   Take exit 226 to merge onto US-11 N, toward I-81/Harrisburg
-   Get onto I-81 S
-   Take exit 47A and merge onto PA-34 S (South Hanover St)
-   Follow PA-34 S for 2.8 miles
-   Turn right into the long driveway for Fallen Tree Farm

### From Scranton

-   Get onto I-81 S
-   Take exit 47A and merge onto PA-34 S (South Hanover St)
-   Follow PA-34 S for 2.8 miles
-   Turn right into the long driveway for Fallen Tree Farm

### From York

-   Get onto I-83 N
-   Use the left lane to take exit 41A and merge onto PA-581 W toward 81 S
-   Use the left lane to take exit 1B and merge onto I-81 S toward Carlisle
-   Take exit 47A and merge onto PA-34 S (South Hanover St)
-   Follow PA-34 S for 2.8 miles
-   Turn right into the long driveway for Fallen Tree Farm

## Hotels

Due to other events in the area the same weekend, a block of rooms at a single
hotel was not reserved. However, there are plenty of hotels nearby.

### Days Inn Carlisle South

[Website](https://www.wyndhamhotels.com/days-inn/carlisle-pennsylvania/days-inn-carlisle-south/overview)

101 Alexander Spring Rd, Carlisle, PA 17015

[(717) 258-4147](tel:1-717-258-4147)

### Days Inn Carlisle North

[Website](https://www.wyndhamhotels.com/days-inn/carlisle-pennsylvania/days-inn-carlisle-north/overview)

1825 Harrisburg Pike , Carlisle, PA 17015

[(717) 245-2242](tel:1-717-245-2242)

### Best Western Carlisle

[Website](https://www.bestwestern.com/en_US/book/hotel-details.39105.html)

1155 Harrisburg Pike, Carlisle, PA 17013

[(717) 243-6200](tel:1-717-243-6200)

Toll-free: [1-800-780-7234](tel:1-800-780-7234)

### Econo Lodge Carlisle

[Website](https://www.choicehotels.com/pennsylvania/carlisle/econo-lodge-hotels/pa655)

1252 Harrisburg Pike, Carlisle, PA 17013

[(717) 243-8585](tel:1-717-243-8585)
